sbatch ${HOME}/julea/enzo-all/slurm__FuzzyDarkMatter_FDMTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_MHDZeldovichPancake_MHDZeldovichPancakeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_SphericalInfall_SphericalInfallenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_AMRZeldovichPancake_Streaming_AMRZeldovichPancake_Streamingenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_MHDAdiabaticExpansion_Dedner_MHDAdiabaticExpansion_Dednerenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_AMRZeldovichPancake_AMRZeldovichPancakeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_MHDZeldovichPancake_2_CT_MHDZeldovichPancake_2_CTenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_ZeldovichPancake_ZeldovichPancakeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_AdiabaticExpansion_AdiabaticExpansionenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_MHDZeldovichPancake_2_Dedner_MHDZeldovichPancake_2_Dednerenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cosmology_MHDAdiabaticExpansion_CT_MHDAdiabaticExpansion_CTenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__DrivenTurbulence3D_DrivenTurbulence3Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cooling_OneZoneFreefallTest_OneZoneFreefallTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cooling_CoolingTest_Cloudy_CoolingTest_Cloudyenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Cooling_CoolingTest_JHW_CoolingTest_JHWenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_FreeExpansionAMR_FreeExpansionAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_ImplosionAMR_ImplosionAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_RampedKelvinHelmholtz2D_RampedKelvinHelmholtz2Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_KelvinHelmholtzAMR_KelvinHelmholtzAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_NohProblem2DAMR_NohProblem2DAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_KelvinHelmholtz_KelvinHelmholtzenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_ValidatedNonlinearKelvinHelmholtz_2D-LongKHenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_ValidatedNonlinearKelvinHelmholtz_2D-LongKH-AMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_ShockPool2D_ShockPool2Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_NohProblem2D_NohProblem2Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_Implosion_Implosionenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_AMRShockPool2D_AMRShockPool2Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_RadiatingShockWave_RadiatingShockWaveenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_Athena-RayleighTaylor_Athena-RayleighTaylorenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_HDMHD2DCheckOddEvenCouplingOfRiemannSolver_HDMHD2DCheckOddEvenCouplingOfRiemannSolverenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_SedovBlastAMR_SedovBlastAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_SedovBlast_SedovBlastenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-2D_DoubleMachReflection_DoubleMachReflectionenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_CollideTest_CollideTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_CollapseTestNonCosmological_CollapseTestNonCosmologicalenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_AgoraGalaxy_AgoraRestartenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_NohProblem3DAMR_NohProblem3DAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_RotatingCylinder_RotatingCylinderenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_StripTest_StripTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_ExtremeAdvectionTest_ExtremeAdvectionTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_NFWCoolCoreCluster_NFWCoolCoreClusterenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_NohProblem3D_NohProblem3Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_ShockPool3D_ShockPool3Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_Athena-RayleighTaylor3D_Athena-RayleighTaylor3Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_GalaxySimulation_GalaxySimulationenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_ProtostellarCollapse_Std_ProtostellarCollapse_Stdenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-3D_RotatingSphere_RotatingSphereenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-4-ShockTube_Toro-4-ShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-6-ShockTube_Toro-6-ShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_WavePool_WavePoolenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_PressurelessCollapse_PressurelessCollapseenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-5-ShockTubeAMR_Toro-5-ShockTubeAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-1-ShockTubeAMR_Toro-1-ShockTubeAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-3-ShockTubeAMR_Toro-3-ShockTubeAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-2-ShockTubeAMR_Toro-2-ShockTubeAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-1-ShockTube_Toro-1-ShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-7-ShockTube_Toro-7-ShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-3-ShockTube_Toro-3-ShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-2-ShockTube_Toro-2-ShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-4-ShockTubeAMR_Toro-4-ShockTubeAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_Toro-5-ShockTube_Toro-5-ShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_ShockInABox_input_shockenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_ShockInABox_ShockInABoxenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_SodShockTube_SodShockTubeAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_SodShockTube_SodShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_FreeExpansion_FreeExpansionenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__Hydro_Hydro-1D_InteractingBlastWaves_InteractingBlastWavesenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__FLD_FLD_LWRadParametersenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__FLD_FLDPhotonTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__RadiationTransport_PhotonTestAMR_PhotonTestAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__RadiationTransport_PhotonTest_PhotonTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__RadiationTransport_PhotonShadowing_PhotonShadowingenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__RadiationTransport_PhotonTestMultiFrequency_PhotonTestMultiFrequencyenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__RadiationTransport_PhotonTestMultiFrequency_OT_PhotonTestMultiFrequencyenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__StarParticle_StarParticleSingleTest_TestStarParticleSingleenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__CosmologySimulation_amr_nested_cosmology_amr_nested_cosmologyenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__CosmologySimulation_ReionizationRadHydro_ReionizationRadHydroenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__CosmologySimulation_amr_cosmology_amr_cosmologyenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__CosmologySimulation_dm_only_dm_onlyenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__CosmologySimulation_ReionizationHydro_ReionizationHydroenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_3D_ShearingBox_ShearingBoxenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_3D_StochasticForcing_StochasticForcingenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_1D_BrioWu-MHD-1D-MHDCT_BrioWu-MHD-1Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_1D_BrioWu-MHD-1D_BrioWu-MHD-1Denzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_1D_MHD_Metal_Advection_Dedner_MHD_Metal_Advection_Dednerenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_1D_MHD_Metal_Advection_CT_MHD_Metal_Advection_CTenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_1D_CR-ShockTube_CRShockTubeenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_MHD2DRotorTest_MHD2DRotorTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_MHDCTOrszagTang_MHDCTOrszagTangenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_MHDCTOrszagTangAMR_MHDCTOrszagTangAMRenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_LoopAdvection_CT_LoopAdvection_CTenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_LoopAdvection_Dedner_LoopAdvection_Dednerenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_SedovBlast-MHD-2D-Gardiner_SedovBlast-MHD-2D-Gardinerenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_Wengen2-CollidingFlow_Wengen2-CollidingFlowenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_RayleighTaylor_CT_Suppressed_RayleighTaylor_CT_Suppressedenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_SedovBlast-MHD-2D-Fryxell_SedovBlast-MHD-2D-Fryxellenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__MHD_2D_MHDDednerOrszagTang_MHDDednerOrszagTangenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_GravityStripTest_GravityStripTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_TestOrbit_TestOrbitenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_TestOrbit_TestOrbitPotentialenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_BinaryCollapse_BinaryCollapseenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_GravityTestSphere_GravityTestSphereenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_TestOrbitMRP_TestOrbitMRPenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_GravityTest_GravityTestenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_BinaryCollapseMHDCT_BinaryCollapseenzo.sh
sbatch ${HOME}/julea/enzo-all/slurm__GravitySolver_MaximumGravityRefinementTest_MaximumGravityRefinementTestenzo.sh
