AR = ['/usr/bin/ar']
ARFLAGS = ['rcs']
BINDIR = '/usr/local/bin'
CC = ['afl-gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('8', '3', '0')
CFLAGS = ['-std=c11', '-fdiagnostics-color', '-Wpedantic', '-Wall', '-Wextra', '-Waggregate-return', '-Wcast-align', '-Wcast-qual', '-Wdeclaration-after-statement', '-Wdouble-promotion', '-Wduplicated-cond', '-Wfloat-equal', '-Wformat=2', '-Winit-self', '-Winline', '-Wjump-misses-init', '-Wlogical-op', '-Wmissing-declarations', '-Wmissing-format-attribute', '-Wmissing-include-dirs', '-Wmissing-noreturn', '-Wmissing-prototypes', '-Wnested-externs', '-Wnull-dereference', '-Wold-style-definition', '-Wredundant-decls', '-Wrestrict', '-Wshadow', '-Wstrict-prototypes', '-Wswitch-default', '-Wswitch-enum', '-Wundef', '-Wuninitialized', '-Wwrite-strings', '-fno-omit-frame-pointer', '-ggdb']
CFLAGS_GCOV = ['-fprofile-arcs', '-ftest-coverage']
CFLAGS_GIO = ['-pthread']
CFLAGS_GMODULE = ['-pthread', '-pthread']
CFLAGS_GTHREAD = ['-pthread', '-pthread']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
CPPPATH_ST = '-I%s'
CXXFLAGS_GIO = ['-pthread']
CXXFLAGS_GMODULE = ['-pthread', '-pthread']
CXXFLAGS_GTHREAD = ['-pthread', '-pthread']
DATADIR = '/usr/local/share'
DATAROOTDIR = '/usr/local/share'
DEFINES = []
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'_POSIX_C_SOURCE': '', 'G_DISABLE_DEPRECATED': '', 'HAVE_LEVELDB': '', 'HAVE_STMTIM_TVNSEC': '', 'HAVE_GMODULE': '', 'GLIB_VERSION_MIN_REQUIRED': '', 'HAVE_LIBMONGOC': '', 'JULEA_BACKEND_PATH': '', 'JULEA_DEBUG': '', 'HAVE_GIO': '', 'HAVE_GLIB': '', 'JULEA_BACKEND_PATH_BUILD': '', 'GLIB_VERSION_MAX_ALLOWED': '', 'HAVE_SQLITE': '', 'HAVE_LIBBSON': '', 'HAVE_GTHREAD': '', 'HAVE_SYNC_FETCH_AND_ADD': '', 'HAVE_GOBJECT': '', 'HAVE_LARGEFILE': '', 'HAVE_LMDB': ''}
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
DOCDIR = '/usr/local/share/doc/julea'
DVIDIR = '/usr/local/share/doc/julea'
EXEC_PREFIX = '/usr/local'
HAVE_GIO = 1
HAVE_GLIB = 1
HAVE_GMODULE = 1
HAVE_GOBJECT = 1
HAVE_GTHREAD = 1
HAVE_LARGEFILE = 1
HAVE_LEVELDB = 1
HAVE_LIBBSON = 1
HAVE_LIBMONGOC = 1
HAVE_LMDB = 1
HAVE_SQLITE = 1
HAVE_STMTIM_TVNSEC = 1
HAVE_SYNC_FETCH_AND_ADD = 1
HTMLDIR = '/usr/local/share/doc/julea'
INCLUDEDIR = '/usr/local/include'
INCLUDES_GIO = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/include/glib-2.0', '/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/lib/glib-2.0/include']
INCLUDES_GLIB = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/include/glib-2.0', '/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/lib/glib-2.0/include']
INCLUDES_GMODULE = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/include/glib-2.0', '/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/lib/glib-2.0/include']
INCLUDES_GOBJECT = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/include/glib-2.0', '/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/lib/glib-2.0/include']
INCLUDES_GTHREAD = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/include/glib-2.0', '/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/glib-2.56.3-y4kalfnkzahoclmqcqcpwvxzw4nepwsi/lib/glib-2.0/include']
INCLUDES_LIBBSON = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/libmongoc-1.9.5-a37k6hbsbanjkqibnmcc3letw7wshirg/include/libbson-1.0']
INCLUDES_LIBMONGOC = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/libmongoc-1.9.5-a37k6hbsbanjkqibnmcc3letw7wshirg/include/libmongoc-1.0', '/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/libmongoc-1.9.5-a37k6hbsbanjkqibnmcc3letw7wshirg/include/libbson-1.0']
INFODIR = '/usr/local/share/info'
JULEA_DEBUG = True
JULEA_FUSE = None
JULEA_HDF = False
JULEA_LEVELDB = '-lleveldb \n'
JULEA_LIBMONGOC = '-I/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/libmongoc-1.9.5-a37k6hbsbanjkqibnmcc3letw7wshirg/include/libmongoc-1.0 -I/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/libmongoc-1.9.5-a37k6hbsbanjkqibnmcc3letw7wshirg/include/libbson-1.0 -lmongoc-1.0 -lssl -lcrypto -lrt -lresolv -lz -lsnappy -lbson-1.0 \n'
JULEA_LIBRADOS = None
JULEA_LMDB = '-llmdb \n'
JULEA_SQLITE = '-lsqlite3 \n'
LDFLAGS_GCOV = ['-lgcov', '--coverage']
LIBDIR = '/usr/local/lib'
LIBEXECDIR = '/usr/local/libexec'
LIBPATH_ST = '-L%s'
LIB_GIO = ['gio-2.0', 'gobject-2.0', 'glib-2.0', 'intl']
LIB_GLIB = ['glib-2.0', 'intl']
LIB_GMODULE = ['gmodule-2.0', 'glib-2.0', 'intl']
LIB_GOBJECT = ['gobject-2.0', 'glib-2.0', 'intl']
LIB_GTHREAD = ['gthread-2.0', 'glib-2.0', 'intl']
LIB_LEVELDB = ['leveldb']
LIB_LIBBSON = ['bson-1.0']
LIB_LIBMONGOC = ['mongoc-1.0', 'ssl', 'crypto', 'rt', 'resolv', 'z', 'snappy', 'bson-1.0']
LIB_LMDB = ['lmdb']
LIB_M = ['m']
LIB_SQLITE = ['sqlite3']
LIB_ST = '-l%s'
LINKFLAGS_GIO = ['-pthread']
LINKFLAGS_GMODULE = ['-pthread', '-Wl,--export-dynamic', '-pthread']
LINKFLAGS_GTHREAD = ['-pthread', '-pthread']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINK_CC = ['afl-gcc']
LOCALEDIR = '/usr/local/share/locale'
LOCALSTATEDIR = '/usr/local/var'
MANDIR = '/usr/local/share/man'
OLDINCLUDEDIR = '/usr/include'
PACKAGE = 'julea'
PDFDIR = '/usr/local/share/doc/julea'
PKGCONFIG = ['/src/julea/julea/dependencies/opt/spack/linux-ubuntu19.04-x86_64/gcc-8.3.0/pkgconf-1.6.0-3hvode5en7wwbe3rekqrjgtic73jri26/bin/pkg-config']
PREFIX = '/usr/local'
PSDIR = '/usr/local/share/doc/julea'
RPATH_ST = '-Wl,-rpath,%s'
SBINDIR = '/usr/local/sbin'
SHAREDSTATEDIR = '/usr/local/com'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
SYSCONFDIR = '/usr/local/etc'
cfg_files = ['/src/julea/julea/build2/include/julea-config.h']
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
define_key = []
macbundle_PATTERN = '%s.bundle'
